### ISSUE TITLE
Add deprecated annotations to elements and attributes dropped in HTML5

### ISSUE THREAD

**Issue by aantron** [ocsigen/tyxml#101]
For example, `a_cellspacing`.

EDIT: Actually, `cellspacing`, in particular, is not allowed in any element in TyXML, and neither are `cellpadding` or `charoff`. Perhaps we should remove them, as with `a_fs_rows` and `a_fs_cols`?

**Comment by Drup** [comment]
> EDIT: Actually, cellspacing, in particular, is not allowed in any element in TyXML, and neither are cellpadding or charoff. Perhaps we should remove them, as with a_fs_rows and a_fs_cols?

Yes.

**Comment by Drup** [comment]
@aantron Are we done with this one ? You annotated lot's of elements.

**Comment by aantron** [comment]
I wouldn't say we are fully done with this. W.r.t. elements and attributes, I think I got all of them, but I wasn't making an effort to be 100% thorough – so I wouldn't guarantee it. W.r.t. attribute values, I did not check at all if some have been deprecated.

**Comment by Drup** [comment]
I think we can close, and add new ones when we discover them. This is not really critical.

**Comment by aantron** [comment]
Sounds right 👍
