### ISSUE TITLE
Possible typo: Format.sprintf instead of Format.asprintf

### ISSUE THREAD

**Issue by darioteixeira** [ocsigen/tyxml#113]
In Tyxml's [API page for the dev version of the Html5 module](http://ocsigen.org/tyxml/dev/api/Html5) there's a brief example using `Format.sprintf`.  Shouldn't it be `Format.asprintf`?  (I'm not very familiar with the `Format` module, but that does seem to be the function that typechecks...)

**Comment by Drup** [comment]
@darioteixeira Thanks! Indeed, it was a typo.
