### ISSUE TITLE
Consider removing the "5" from "Html5"

### ISSUE THREAD

**Issue by aantron** [ocsigen/tyxml#116]
Against using "HTML5" in the API:

- If a new major version of the HTML spec comes out (HTML6?), `Html5` and `[%html5]` will look dated, but they will have to be kept for compatibility.
- W3C calls the language "HTML." "HTML5" is just part of the title of the current spec (and, IIRC, an abbreviation for it).
- The WhatWG Living Standard doesn't have a concept of HTML5 (IIRC).
- TyXML trees can be serialized to syntax other than HTML5, such as (non-polyglot) XHTML.

One point in favor might be that a future revision of HTML might not be backwards-compatible with HTML5 and earlier versions. However, W3C hasn't made a serious breaking change to date, except for deprecating features. Those can be handled with deprecation annotations. Indeed, XHTML apparently did not catch on due to breaking changes, so W3C and WhatWG are likely to avoid them in the future.

HTML5 should, of course, be used in documentation and announcements, as long as it is the most recent major version of HTML :)

Compatibility for existing code using module `Html5` can be accomplished by making the `Html5*` modules `include` the corresponding `Html*` modules. Perhaps TyXML can silently stop mentioning the `Html5*` modules in the documentation. I haven't tested it, but I wonder if `[@@@ocaml.deprecated]` works at the module level?

New code should probably just use "HTML", e.g. `[%html]` for the PPX.

**Comment by Drup** [comment]
Done!
