### ISSUE TITLE
Simple svg circle

### ISSUE THREAD

**Issue by nickbetteridge** [ocsigen/tyxml#129]
I would be very grateful if someone could quickly look at my attempt to draw a circle - I've tried quite a few permutations with little success:

```
let start (igor:#Dom.node Js.t) =
  Lwt.catch
    (fun () ->
      let open Tyxml_js.Svg in
      let my_circle = circle ~a:[a_cx "50" ; a_cy "50" ; a_r "40" ; a_stroke "green" ; a_stroke_width "4" ; a_fill "yellow"] in
      let my_svg =  svg ~a:[a_width "100" ; a_height "100"] in
      Dom.appendChild igor (Tyxml_js.To_dom.of_node my_svg);
      return ()
    )
    (fun ex ->
      raise ex
    )

let () =
  match Dom_html.tagged (Dom_html.getElementById "de_main") with
  | Dom_html.Div d -> Lwt_js_events.async (fun () -> start d)
  | _ -> failwith "Bad tree element"
```
with the error referring to let my_circle ....
```
Error: This expression has type string but an expression was expected of type
         Svg_types.Unit.length Tyxml_js.Svg.wrap =
           float *
           [ `Cm | `Em | `Ex | `In | `Mm | `Pc | `Percent | `Pt | `Px ]
           option
```

**Comment by slegrand45** [comment]
It's something like
```ocaml
... circle ~a:[a_cx (50., Some `Px); a_cy (50., Some `Px); a_r (40., Some `Px) ...
```

See https://github.com/slegrand45/examples_ocsigen/blob/master/jsoo/pico-spreadsheet/spreadsheet.ml#L145-L154 for an example if it can help

**Comment by Drup** [comment]
Svg is a a case where the new upcomming ppx is much nicer than the API:

```ocaml
let my_svg = 
  let open Tyxml_js in
  [%svg {|
    <svg width=100 height=100>
    <circle cx=50 cy=50 r=40 stroke="green" stroke_width=4 fill="yellow" />
    </svg>|}] 
```

Unfortunately, you need to wait for the next release to be able to use it. :)

**Comment by nickbetteridge** [comment]
@slegrand45 Thanks for that - when you start out, even the most simple, most obvious things confound

@Drup yes, I know :) I just tried to pin head and discovered that I'd lost irmin by way of js_of_ocam - roll on the next release :)

**Comment by Drup** [comment]
Contribution of an svg-only example would be very appreciated. ;)

**Comment by nickbetteridge** [comment]
Yes, I was thinking about that too - let me ask a few more, brain-dead, questions over the next couple of weeks and then I'll put together something with htlm and svg.

**Comment by Drup** [comment]
I think we can close that one, Feel free to open a PR for your example.
