### ISSUE TITLE
Please: install the PPX by default for usability

### ISSUE THREAD

**Issue by aantron** [ocsigen/tyxml#147]
TyXML should come ready with its own PPX. I shouldn't have to mind special instructions to get it. What is the penalty from installing it?

- The PPX reduces the amount of up-front learning to use TyXML.
- The PPX "knows" TyXML's irregularities, and replaces everything with familiar HTML and SVG syntax. Especially in the case of SVG, consider e.g.: https://github.com/ocsigen/tyxml/issues/129#issuecomment-211918425. It takes many trips to the docs to figure combinators out for even relatively simple elements. The PPX simplifies this considerably, so it is not a second-class part of TyXML.
- We know there at least some people excited about the PPX. This gives "some" idea that "people" think the PPX important for TyXML.

Given that, there shouldn't be an artificial stumbling block on the way to using it. This especially concerns OCaml/OPAM newbies, who may not see the [message](https://github.com/ocsigen/tyxml/blob/master/opam#L47) and may not be able to readily diagnose why TyXML is "not working."

Also, a user of TyXML shouldn't have to make `markup` into a root (explicitly chosen) package just to fully use TyXML. Indeed, there is no reason why a user of TyXML should be particularly aware of `markup` at all, any more than `re` or `uutf`.

**Comment by aantron** [comment]
Not to mention that, as of now, a package that depends on TyXML and uses the PPX syntax would have to have an artificial dependency on `markup` (and maybe `ppx_tools`?) in order to be properly packaged (I think).

**Comment by Drup** [comment]
Alternative solution suggested by @rgrinberg, which is the one that I was planning to implement: Add a virtual opam package, `tyxml_ppx` (or whatever) that pulls everything needed, similarly to `mirage-conduit`.

**Comment by aantron** [comment]
What problem is avoided by not installing the PPX?

**Comment by Drup** [comment]
We had this discussion already, I don't want to redo it. We will see how adoption goes, but for now, the ppx will stay optional. I may revisit this decision later on.

I agree about you on the usability problem, and the `tyxml_ppx` package solves that.

**Comment by aantron** [comment]
> We had this discussion already, I don't want to redo it.

We had a similar discussion in private, but

- I didn't raise most of the points that I raised in this issue,
- you did not mention the `tyxml_ppx` plan, which is good to know, and
- it was not open to comment from 3rd persons because it was in a private IRC chat.

so it seems worthwhile.

**Comment by Drup** [comment]
My opinion is the following: the lighter/more modular, the better. This is true for both what is linked in, and what is compiled by the user. In particular, if most users don't need the ppx, we should not install the ppx by default, it's that simple. It's a general behavior across all package. I made the camlp4 extension optional for similar reasons and I want to explode eliom in smaller packages for the same reasons.

Of course, There is the usability problem, which I'm well aware of, hence the `tyxml_ppx` package.

**Comment by vasilisp** [comment]
TyXML is a hard dependency of Ocsigen Server, Eliom, Lambdoc, and possibly other projects. It is clearly also needed for the (IMHO important) `Tyxml_js` module of `Js_of_ocaml`. All these work perfectly fine without TyXML's PPX. So please don't introduce a fake and unneeded dependency for the transitive closure of TyXML's reverse dependencies.

Look at all the trouble that Ruby, Node.js et al. have because of their insane dependency graphs :).

**Comment by aantron** [comment]
Fair enough. The `tyxml_ppx` package idea does resolve a lot of the issues.
