### ISSUE TITLE
Could \n between <option> inside <select> be allowed in ppx?

### ISSUE THREAD

**Issue by pirbo** [ocsigen/tyxml#159]
Compilation of
```
module Html = Tyxml_js.Html5
let%html fail = {|<select>
                  <option value="bar">bar</option>
  </select>|}
```
fails with the error
```
Error: This expression has type
         ([> `Option | `PCDATA ] as 'a) Html.elt Html.Xml.W.tlist =
           'a Html.elt list
       but an expression was expected of type
         ([< Html_types.select_content_fun ] as 'b) Html.elt Html.list_wrap =
           'b Html.elt list
       Type 'a Html.elt = 'a Tyxml_js.Html.elt is not compatible with type
         'b Html.elt = 'b Tyxml_js.Html.elt 
       Type [> `Option | `PCDATA ] as 'a is not compatible with type
         'b = [< `Optgroup | `Option ] 
       The second variant type does not allow tag(s) `PCDATA
```
Indeed ```ocamlfind ppx_tools/rewriter ppx_tyxml /tmp/foo.ml``` answers:
```
let fail =
  Html.select
    (Html.Xml.W.cons (Html.pcdata "\n                  ")
       (Html.Xml.W.cons
          (Html.option ~a:[Html.a_text_value (Html.Xml.W.return "bar")]
             (Html.Xml.W.return (Html.pcdata "bar")))
          (Html.Xml.W.cons (Html.pcdata "\n  ") (Html.Xml.W.nil ()))))
```
The select must be only on 1 line to make it work:
```
module Html = Tyxml_js.Html5
let%html fail = {|<select><option value="bar">bar</option></select>|}
```
Is this a deep limitation or a simple bug?

**Comment by Drup** [comment]
markup.ml is supposed to ignore some of the whitespace when they are not relevant. It should probably do so in this case. I will wait for @aantron's answer on this one.

**Comment by aantron** [comment]
Markup.ml is acting correctly here, see the [HTML spec](https://www.w3.org/TR/html5/syntax.html#parsing-main-inselect) (in select, "Any other character token" [other than `\x00`] is inserted ("returned")). However, this behavior probably isn't what the PPX should do.

@Drup, you can:

- Pass the Markup.ml [signal stream](https://github.com/ocsigen/tyxml/blob/2f19cab76b80c21904aac20cdf34bdcc903bff7f/ppx/ppx_tyxml.ml#L296) through [`Markup.trim`](http://aantron.github.io/markup.ml/#VALtrim) (and probably `Markup.normalize`) to get rid of whitespace like this globally. `trim` actually probably is wrong for `<pre>` tags, so we should add some kind of `trim_html` function that handles those correctly, or modify `trim`, if you want to go this route.
- Make a custom [assembly function](https://github.com/ocsigen/tyxml/blob/2f19cab76b80c21904aac20cdf34bdcc903bff7f/ppx/ppx_element_content.mli#L68) for `<select>`, as we already have for some element types, that calls [`filter_whitespace`](https://github.com/ocsigen/tyxml/blob/2f19cab76b80c21904aac20cdf34bdcc903bff7f/ppx/ppx_element_content.ml#L57) and [then acts like `star`](https://github.com/ocsigen/tyxml/blob/2f19cab76b80c21904aac20cdf34bdcc903bff7f/ppx/ppx_element_content.ml#L106).

The second is probably the better idea.
