### ISSUE TITLE
ppx and empty textarea

### ISSUE THREAD

**Issue by pirbo** [ocsigen/tyxml#160]
Not critical by I lost quite some time on it so I submit to discuss whether it is worth fixing:
```let%html fail = {|<textarea></textarea>|}```
fails with an empty error message.
It is because Html.textarea misses its Html.pcdata argument.
```let%html ok = {|<textarea> </textarea>|}``` is correctly understood as ```let ok = Html.textarea (Html.Xml.W.return (Html.pcdata " "))```

**Comment by Drup** [comment]
The empty error message comes from a bug that was fixed in the dev version. In the dev version, you will get:

```ocaml
# let%html fail = {|<textarea></textarea>|} ;;
Error: textarea should have exactly one child      
```

**Comment by Drup** [comment]
Closing, since I don't think we should do more about this. The error message seems clear to me. I'm not convinced we should insert `pcdata ""` magically when there are no children.

Release should be soon™
