### ISSUE TITLE
Mismatch between tyxml.opam's message and the actual package name

### ISSUE THREAD

**Issue by Armael** [ocsigen/tyxml#162]
`tyxml.opam` mentions "tyxml_ppx", while the package currently in the opam repository is named "tyxml-ppx".

**Comment by nlko** [comment]
Hello, 

Same mistake on this page : https://ocsigen.org/tyxml/

```
opam install tyxml_ppx
```
instead of 
```
opam install tyxml-ppx
```

**Comment by vasilisp** [comment]
I fixed the website, thanks.

**Comment by Drup** [comment]
@Armael I forgot about that bug report .. thanks, now fixed. :)
