### ISSUE TITLE
International characters encoding in HREF attributes

### ISSUE THREAD

**Issue by orbifx** [ocsigen/tyxml#163]
Tyxml escapes HREF attributes containing UTF8 characters with forward slashes (\), instead of percentage encoding.

For example the following code

    a ~a:[a_href ("/text/" ^ utf_str)] [Unsafe.data utf_str]

with  `utf_str=λαμδα` produces:

    <a href="/text/\206\187\206\177\206\188\206\180\206\177">λαμδα</a> 

which the browser and opium don't seem to like.

**Comment by Drup** [comment]
@vouillon you did most of the stuff related to encoding, do you have an opinon on that one ?

**Comment by orbifx** [comment]
I'm using `Unsafe.data <a href="unicode...`  as a work around for now.

**Comment by Drup** [comment]
Well, this was not related to encoding at all in the end, just to an idiotic use of `%S` for pretty printing (And I was the idiot :O)...

Thanks for the report!

**Comment by orbifx** [comment]
So long it's found :)
