### ISSUE TITLE
dependency on `markup` incorrect / missing?

### ISSUE THREAD

**Issue by mor1** [ocsigen/tyxml#167]
After a current `opam update -yu`, `opam install tyxml` complains of missing package `markup` -- although isn't that only supposed to be a dependency of `tyxml-ppx`? -- as well as complaining of missing package `wikidoc`.

`opam install markup` appears to fix things to the point that `opam install tyxml` works.

**Comment by vasilisp** [comment]
It should be optional. I personally don't have `markup` in my standard OPAM switch.

Maybe OPAM is using the internal solver? That one causes frequent trouble, you could try installing `aspcud` or similar. See https://opam.ocaml.org/doc/Install.html#ExternalSolvers.

**Comment by mor1** [comment]
I think I'm already using `aspcud` viz:

```
: mort@greyjay:~$; opam config report
# OPAM config report
# opam-version    1.2.2
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  system*
# last-update     2016-11-21 19:05
```

**Comment by Drup** [comment]
It's difficult to answer your question without the opam log. :/

**Comment by mor1** [comment]
Well, in attempting to repro, the following log looks relevant:

```
: mort@greyjay:tlstunnel#unikernelise= $; opam remove markup
The following actions will be performed:
  ⊘  remove    markup 0.7.2
  ↻  recompile tyxml  4.0.1                   [uses markup]
       For tyxml's ppx, please install tyxml-ppx.
===== ↻  1   ⊘  1 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[tyxml] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
⊘  removed   tyxml.4.0.1
⊘  removed   markup.0.7.2
[ERROR] The compilation of tyxml failed at "ocaml setup.ml -doc".
Processing  3/3: [tyxml: ocamlfind remove]
#=== ERROR while installing tyxml.4.0.1 =======================================#
# opam-version 1.2.2
# os           darwin
# command      ocaml setup.ml -doc
# path         /Users/mort/.opam/system/build/tyxml.4.0.1
# compiler     system (4.03.0)
# exit-code    1
# env-file     /Users/mort/.opam/system/build/tyxml.4.0.1/tyxml-14111-ad8886.env
# stdout-file  /Users/mort/.opam/system/build/tyxml.4.0.1/tyxml-14111-ad8886.out
# stderr-file  /Users/mort/.opam/system/build/tyxml.4.0.1/tyxml-14111-ad8886.err
### stdout ###
# /Users/mort/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -keep-locs -strict-sequence -I lib -warn-error +1..49 -warn-error -45-3 -w A-4-9-40-42-44-48 -package uutf -package re -I lib -I implem -o implem/tyxml_xml.cmi implem/tyxml_xml.mli
# /Users/mort/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -keep-locs -strict-sequence -I lib -warn-error +1..49 -warn-error -45-3 -w A-4-9-40-42-44-48 -package uutf -package re -I lib -I implem -o implem/tyxml_svg.cmi implem/tyxml_svg.mli
# /Users/mort/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -keep-locs -strict-sequence -I lib -warn-error +1..49 -warn-error -45-3 -w A-4-9-40-42-44-48 -package uutf -package re -I lib -I implem -o implem/tyxml_html.cmi implem/tyxml_html.mli
# /Users/mort/.opam/system/bin/ocamlfind ocamldep -package ppx_tools.metaquot -package bytes -package re.str -package markup -modules ppx/ppx_tyxml.mli > ppx/ppx_tyxml.mli.depends
# + /Users/mort/.opam/system/bin/ocamlfind ocamldep -package ppx_tools.metaquot -package bytes -package re.str -package markup -modules ppx/ppx_tyxml.mli > ppx/ppx_tyxml.mli.depends
# ocamlfind: Package `markup' not found
# Command exited with code 2.
### stderr ###
# ocamlfind: Package `wikidoc' not found
# E: Failure("Command ''/Users/mort/.opam/system/bin/ocamlbuild' ./tyxml-api.docdir/index.html -use-ocamlfind -tag debug' terminated with error code 10")



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions failed
  ∗  install tyxml 4.0.1
The following changes have been performed
  ⊘  remove markup 0.7.2
  ⊘  remove tyxml  4.0.1

The former state can be restored with:
    opam switch import "~/.opam/system/backup/state-20161022095136.export"
```

**Comment by mor1** [comment]
Aha! This was because I have `OPAMBUILDDOC=true` in my environment by default; unsetting it means the install works ok. 

Now -- I don't know enough OPAM. Is there some way to tell OPAM to install `markup` only if performing a doc build?

**Comment by nilsbecker** [comment]
i just ran into the same problem: with OPAMBUILDDOC=true the installation fails because markup is missing. 

the great majority of packages install fine for me when OPAMBUILDDOC=true. it would be nice if tyxml could fix this. brute force solution would be to add these extra dependencies unconditionally?

**Comment by Drup** [comment]
There is a `{doc}` filter in opam 2.0, but not in the previous versions, so we can't really fix that at the moment.

That being said, you don't really need that variable, just use odig instead. :p

**Comment by nilsbecker** [comment]
hm, ok, so maybe it's time to switch to a more modern doc generation? but will odig let me lookup docs within merlin? (not sure what that functionality depends on)

**Comment by Drup** [comment]
Doc lookup in merlin depends on `cmt(i)` being compiled installed, which is the case by default, and need neither OPAMBUILDDOC nor odig.

**Comment by jberdine** [comment]
FWIW, I just hit this same issue as I happened to have OPAMBUILDDOC set. It would have been helpful if there was some more direct way to realize that this variable was the source of the build failure, but I don't really know how that could be done. If I hadn't come here to report a missing dependency bug, I wouldn't have found the real explanation.

**Comment by Drup** [comment]
We switched to jbuilder, all optional dependencies are gone, so this should be fixed!
