### ISSUE TITLE
tyxml.ppx / lwt.ppx conflict?

### ISSUE THREAD

**Issue by sagotch** [ocsigen/tyxml#178]
```
js_of_eliom -ppx -o local/var/www/foo/eliom/foo.js  \
-package lwt.ppx -package js_of_ocaml.ppx -package js_of_ocaml.deriving.ppx \
-package tyxml.ppx _client/foo.cmo

File "/home/ju/.opam/4.04.1/lib/lwt/ppx.cma(Ppx_lwt)", line 1:

Warning 31: files /home/ju/.opam/4.04.1/lib/lwt/ppx.cma(Ppx_lwt) and 
/home/ju/.opam/4.04.1/lib/lwt/ppx.cma(Ppx_lwt) both define a module named Ppx_lwt

File "_none_", line 1:

Error: Some fatal warnings were triggered (1 occurrences)
```

But this one is fine (removing the lwt.ppx package).
```
js_of_eliom -ppx -o local/var/www/foo/eliom/foo.js  \
-package js_of_ocaml.ppx -package js_of_ocaml.deriving.ppx \
-package tyxml.ppx _client/foo.cmo
```
Is it meant to be like this? (And where does this *bug* come from?)

**Comment by vasilisp** [comment]
The issue has been discussed [in the mailing list](https://sympa.inria.fr/sympa/arc/ocsigen/2016-12/msg00019.html).

I think we can implement a workaround in `js_of_eliom` (filter the `-I` flags we get from findlib). I should get around to this.

**Comment by Drup** [comment]
Since this is not something that will be solved on the tyxml side, closing!
