### ISSUE TITLE
Missing cmi for Ppx_common

### ISSUE THREAD

**Issue by Armael** [ocsigen/tyxml#179]
`Ppx_tyxml` (in ocamlfind package `tyxml.ppx.internal`) is currently not usable as a library, as a cmi seems to be missing for module `Ppx_common`. `Ppx_common` is required as `Ppx_tyxml.markup_to_expr` takes an argument of type `Ppx_common.lang`.

**Comment by Drup** [comment]
I won't take time to do it in the very short term, but PR very welcome.

**Comment by Armael** [comment]
Closed by #180
