### ISSUE TITLE
Html_sigs.T should avoid using Variants

### ISSUE THREAD

**Issue by shepard8** [ocsigen/tyxml#182]
The [Html_sigs.T](https://ocsigen.org/tyxml/dev/api/Html_sigs.T) module is inconsistent in its use of the types defined in [Html_types](https://ocsigen.org/tyxml/dev/api/Html_types). Most of the time it makes use of these, but in some occasions it redefines the types.

In my opinion this is bad for several reasons:
- Code duplication (the types are always already defined in Html_types);
- Error-prone (Indeed, I spotted two inconsistencies between Html_sigs.T and Html_types);
- Less readable;
- Bloats the Html_sigs.T interface.

I compiled a list of the places where variants are used instead of dedicated types.

Elements signatures not using their associated attrib type:

iframe
object
embed
area
fieldset
optgroup
details
command
menu
link

Elements signatures not using their associated content type:

footer (uses flow5_without_header_footer)
header (uses flow5_without_header_footer)
bdo (uses phrasing)
iframe
fieldset (uses flow5)
optgroup
details (uses flow5)

Elements signatures not using their associated output type:

footer
header
bdo
a
del
ins
iframe
object (!! the types do not agree on Object_interactive variant)
embed
area
map (!! the types do not agree : Map versus A)
fieldset
datalist
optgroup
details
command
menu
link

**Comment by shepard8** [comment]
I can prepare a pull request for that one, but I need maintainer's advice (I guess that means @Drup's advice) about what to do with the two inconsistencies. My advice would be to follow Html_types in both cases : 

- The map element is surely not represented by an HTML `A` tag, (obviously a `map` element is distinct from an `a` element);
- For the object element, I guess the Object_interactive variant is meant to be used when the usemap attribute is present. However I suspect this is not currently implemented. Maybe this element deserves another issue on its own. In any case using the wider type from Html_types does no harm.

**Comment by Drup** [comment]
In general, I completely agree. This is something that I usually fix along the way. However, be very careful about some of the types that might be different on purpose. I would be prefer if you would separate the obvious fixes and the non-obvious ones.
You might be interested by this: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories

And indeed, the Map element sounds like a bug, but it's probably made for convenience, since the rules should be almost the same.  
For the Object element, I would have to take a closer look at the spec. 

Keep in my mind that, ultimately, tyxml is supposed to be convenient to use. This means we don't always want to enforce all the insanity present in the spec. ;)

**Comment by Drup** [comment]
Also, tests on authorized and forbidden compositions of elements are very welcome. Tests that do not type can be put into the file `html_fail.top.ml`

**Comment by shepard8** [comment]
Okay, I'll be very careful while changing types.

Being so, I spot another mismatch:

- area in Html_sigs.T does not accept attribute Download, while Html_types does.

If I find another mismatches, I'll edit this post to keep track of them in a single place.

**Comment by shepard8** [comment]
I went a bit fast on your sentence about the map element. I thought you agreed on the fact it was to be fixed, while you did not ^^ I can revert that and propose another pull request without that change if needed.

**Comment by Drup** [comment]
@shepard8 I rather agree, actually. But It mostly means I have to look more closely at both the spec and the types. :)
