### ISSUE TITLE
Merge attributes of the same name (class for example), rather than ignoring the second one.

### ISSUE THREAD

**Issue by balat** [ocsigen/tyxml#196]
It is very convenient to be able to have several class attributes.
A very common pattern is:
```
let myelement ?(a = []) () =
  div ~a:( a_class [ "myelement" ] :: a) [ ... ]
```
In the current implementation of Tyxml, classes defined in `?a` are ignored, which is wrong.

This is fixed in Eliom, for `class` only. See for example:
https://github.com/ocsigen/eliom/commit/ca7a2d013a901fb5d0ea8dbb5f5e74684ce2cc97

But we should generalize this all comma separated and space separated attributes, and do the same in Tyxml.

Vincent

**Comment by Drup** [comment]
Already reported in https://github.com/ocsigen/tyxml/issues/69, and the answer I gave is still valid: attributes are abstract and can't be opened on tyxml's side. We need to extend the base module's signature to be able to do that.

Fortunately, a new major version of tyxml is on the horizon, so we can break compat. I can take a look if that's difficult to do, but I'm afraid it's not going to play well with wraping/reactive elements.

I just want to clarify one misunderstanding: tyxml doesn't *ignore* anything. Individual implementations of the xml data structure might ignore things, but that's a bug in their implementation. In particular:
```ocaml
# #require "tyxml" ;;
# Tyxml.Html.(div ~a:[a_class ["foo"] ; a_class ["bar"]] []) ;;
- : [> Html_types.div ] Tyxml_html.elt = <div class="foo" class="bar"></div>
```
It's not spec compliant, but nothing is lost.

Closing in favor of the older bug report.
