### ISSUE TITLE
Missing archive for version 2.2.0

### ISSUE THREAD

**Issue by samoht** [ocsigen/tyxml#203]
It seems that http://ocsigen.org/download/tyxml-2.2.0.tar.gz is not valid anymore but:

```
$ opam info tyxml.2.2.0 -f url.src:
http://ocsigen.org/download/tyxml-2.2.0.tar.gz
```

**Comment by Drup** [comment]
*sight*
Yet another consequence of the new ocsigen website.

@balat @CelieArnaud Do you still have the tarballs around?

**Comment by Drup** [comment]
The tarball is back!
