### ISSUE TITLE
Installation of tyxml-ppx via opam does not work

### ISSUE THREAD

**Issue by loxs** [ocsigen/tyxml#208]
Seems like `opam install tyxml-ppx` will finish without an error, though the package does not get installed.
Nothing gets written to `~/opam/<switch>/lib/tyxml-ppx/`

On the other hand, if you do something like `opam pin add tyxml-ppx --dev-repo` it does get installed properly.

My environment is Mac OS with Opam 2.0.0 and 4.07 switch.

**Comment by Drup** [comment]
Did you pin only `tyxml` but not `tyxml-ppx` before ? If so, that is expected.

**Comment by loxs** [comment]
No, initially I tried installing the non-pinned version of both tyxml and tyxml-ppx

**Comment by Drup** [comment]
Is that still the case ? It seems like nothing we can really do anything about, until the new release which uses dune.

**Comment by loxs** [comment]
Yes, just tried it again and it's exactly as described in the first comment.

**Comment by Drup** [comment]
I'm still unclear of what you did. Which version of tyxml and tyxml-ppx do you have, and which version did you try to install, in which order ?

**Comment by loxs** [comment]
1. Start with an empty switch or one which doesn't have tyxml-ppx installed.

2. `opam install tyxml-ppx`

3. No files get installed:
```
$ ls -lh ~/.opam/ocaml-base-compiler.4.07.0/lib/tyxml-ppx/
ls: /Users/loxs/.opam/ocaml-base-compiler.4.07.0/lib/tyxml-ppx/: No such file or directory
```

4. Try pinning to dev:
```
$ opam pin add tyxml-ppx --dev-repo
[tyxml-ppx.4.2.0] synchronised from git+https://github.com/ocsigen/tyxml.git
tyxml-ppx is now pinned to git+https://github.com/ocsigen/tyxml.git (version dev)

The following actions will be performed:
  - upgrade tyxml-ppx 4.2.0 to dev*
Do you want to continue? [Y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> removed   tyxml-ppx.4.2.0
-> installed tyxml-ppx.dev
Done.
```

5. Now all is good:
```
$ ls -lh ~/.opam/ocaml-base-compiler.4.07.0/lib/tyxml-ppx/
total 21832
-rw-r--r--   1 loxs  staff   749B Oct  5 09:30 META
drwxr-xr-x  72 loxs  staff   2.3K Oct  5 09:30 internal
-rw-r--r--   1 loxs  staff   527B Oct  5 09:30 opam
-rwxr-xr-x   1 loxs  staff    11M Oct  5 09:30 ppx.exe
-rw-r--r--   1 loxs  staff    12B Oct  5 09:30 tyxml-ppx.dune
-rw-r--r--   1 loxs  staff   2.2K Oct  5 09:30 tyxml_ppx_register.a
-rw-r--r--   1 loxs  staff   3.2K Oct  5 09:30 tyxml_ppx_register.cma
-rw-r--r--   1 loxs  staff   1.3K Oct  5 09:30 tyxml_ppx_register.cmi
-rw-r--r--   1 loxs  staff    11K Oct  5 09:30 tyxml_ppx_register.cmt
-rw-r--r--   1 loxs  staff   1.4K Oct  5 09:30 tyxml_ppx_register.cmx
-rw-r--r--   1 loxs  staff   1.4K Oct  5 09:30 tyxml_ppx_register.cmxa
-rw-r--r--   1 loxs  staff   9.7K Oct  5 09:30 tyxml_ppx_register.cmxs
-rw-r--r--   1 loxs  staff   109B Oct  5 09:30 tyxml_ppx_register.ml
```

**Comment by Drup** [comment]
Ah, that's normal. Stable version of tyxml-ppx is a virtual package for tyxml's optional dependencies. Everything is installed in `tyxml`. You shouldn't look into directories like that directly. Use ocamlfind instead.
