### ISSUE TITLE
Xml & Svg : namespace conflict  

### ISSUE THREAD

**Issue by hhugo** [ocsigen/tyxml#22]
`Xml` & `Svg` can easily collide with other libraries.
It would be better to have them packed.

**Comment by sagotch** [comment]
While waiting for a fix, is there any workaround for using another lib with a xml module?

```
ocsigenserver: ocsigen:main: Fatal - While loading /[...]/.opam/4.02.3/lib/xml-light/xml-light.cma: interface mismatch on Xml
```

**Comment by Drup** [comment]
Fixed in master.
