### ISSUE TITLE
Unknown attribute type on source element

### ISSUE THREAD

**Issue by Julow** [ocsigen/tyxml#229]
The `type` attribute is not recognized (`Error: Unknown attribute in HTML element: type`) in

```
<source src="foo.mp3" type="audio/mpeg">
```

**Comment by Drup** [comment]
The associated attribute is `Html.a_mime_type` (there are several distinct `type` attribute, so it's disambiguated. Apparently, we are missing a smart constructor for the `source` html element in the ppx.
