### ISSUE TITLE
Tyxml and seq

### ISSUE THREAD

**Issue by hhugo** [ocsigen/tyxml#238]
Tyxml seems to have dependency on Seq (looking at sources and the opam file) but not dependency on seq is defined in dune files ? How does that work ?

**Comment by Drup** [comment]
Yes, it's an error on my part. it works out ok for recent versions of `re`, since `re` depends on `seq`, but it causes an issue otherwise which I didn't got time to fix.

**Comment by jordwalke** [comment]
I believe newer versions of Dune may block undeclared transitive dependencies leaking, is that the case? If so, I think this would/will crop up again.

**Comment by Drup** [comment]
This is solved in the last few version, and manually patched in opam for the other versions.
