### ISSUE TITLE
ppx: script tag should be allowed to have no child

### ISSUE THREAD

**Issue by adrien-n** [ocsigen/tyxml#245]
The following are rejected by the ppx:

    <script src="foo"></script>

with the following error: `Error: Error: script should have exactly one child`.

It is quite easy to work around the issue by inserting a space inside the tag (but it's not obvious).

**Comment by Drup** [comment]
This is due to the fact that `script` is marked as `unary`.

We could technically mark it as `star`, but that would be a breaking change, so I'll keep it for later.

**Comment by ghuysmans** [comment]
Hi,
It looks like this issue was solved in 0d8539643205227519c59c88ef42ed9698548fbb.

**Comment by smorimoto** [comment]
Yes, it has actually been fixed: https://github.com/ocsigen/tyxml/blob/47423cf70b804c67386583a9b7eccd9157316475/test/test_ppx.ml#L206-L212
