### ISSUE TITLE
Script tag breaks javascript code

### ISSUE THREAD

**Issue by vrama628** [ocsigen/tyxml#272]
I'm trying to insert some javascript into a `Tyxml.Html` document, but when I try something like this:
```
Tyxml.Html.(
  script (txt "alert(\"HELLO\")")
)
```
TyXML outputs the following HTML code:
```
<script>alert(&quot;HELLO&quot;)</script>
```
It replaces the quotation marks in the javascript code with HTML escape sequences, which breaks the javascript code. What is the intended way to use `Tyxml.Html.script` to insert javascript into a page?

**Comment by hhugo** [comment]
Have you tried to use pcdata instead of txt

**Comment by vrama628** [comment]
When I use `pcdata` instead of `txt` I get a build failure because `pcdata` is deprecated:
```
File "foo.ml", line 57, characters 9-15:
57 |         (pcdata "alert(\"HELLO\")")
              ^^^^^^
Error (alert deprecated): Tyxml.Html.pcdata
Use txt instead
```

**Comment by hhugo** [comment]
cdata_script ?

**Comment by vrama628** [comment]
Thanks, that seems to work, although it also inserts these weird comments before and after the javascript code that I don't understand the purpose of:
```
<script>
//<![CDATA[
alert("HELLO")
//]]>
</script>
```
Those comments don't break the behavior of the javascript though, so this works for my use case. It seems like there are many ways to insert text in TyXML, each with their own additional behavior that escapes HTML characters, inserts comments, etc. For my future reference, are the behaviors of these things documented anywhere?
