### ISSUE TITLE
`a_on` for custom events?

### ISSUE THREAD

**Issue by smondet** [ocsigen/tyxml#276]
How would one set handler for one of those within Tyxml (I'm using Tyxml_lwd but same question for classic Tyxml_js):
https://getbootstrap.com/docs/4.5/components/collapse/#events

**Comment by Drup** [comment]
That's a good question. The main issue is that, AFAIK, it's not possible to create such event handler only with markup., which is what tyxml does. What you could do is use `Lwt_js_event` to set them.

If you have a proposal to adjust `Tyxml_js` to be able to set custom events, I'm all hear, but currently, it doesn't really fit.

(How do you like `tyxml_lwd` ? :) )

**Comment by smondet** [comment]
Indeed `Lwt_js_Events` or just the `Dom_html.handler` stuff works for what I'm doing.

This ends up being completely off-topic but may be useful to people landing here with a search engine ☺ :

Bootstrap's jQuery events are not _really_ usable as js-events & I have no idea whether or how one could catch them outside of jQuery (names are mangled with namespaces and such).

The only way I managed to get them to `Dom_html.addEventListener`/`Js_of_ocaml_lwt.Lwt_js_events.make_event` is by "forwarding" them (which seems quite inefficient?):

```javascript
// in a <script> in the document …
$(document).on('shown.bs.collapse', function (e) {
   console.log('------------- hello --------- ' + e.type);
   var ev = new CustomEvent('collapse-shown');
   document.body.dispatchEvent(ev);
})
```

and then catch the event `"collapse-shown"` …


-------


**`Tyxml_lwd`**

After hitting a few bugs (that @let-def fixed extremely fast — and it's because I must have been the first real user), it's been quite pleasant.

All in all, it's not that different from `Tyxml_js.R`, but the API feels way cleaner (e.g. it seems that there is no `React.S.value` or `==` *Russian Roulette* `;)`), and there is no separate `ReactiveData` that gets in the way.
