### ISSUE TITLE
inputmode="decimal"?

### ISSUE THREAD

**Issue by joelburget** [ocsigen/tyxml#278]
Hi there, I noticed tyxml rejects [`inputmode="decimal"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode). Should it be allowed? I also noticed several input modes I don't see referenced in the Mozilla docs (verbatim, latin, etc). I'm curious where the list comes from.

https://github.com/ocsigen/tyxml/blob/4d48e60269dc5d2f7ad62f8ef5af05b7b9e11042/lib/html_sigs.mli#L329-L333

**Comment by Drup** [comment]
It probably comes from the old XHTML attributes. It should definitely be updated! Do you want to take a shot at it ?

**Comment by joelburget** [comment]
Sure thing, I'll send over a PR a bit later today.
