### ISSUE TITLE
Extend `autocomplete` attribute values

### ISSUE THREAD

**Issue by aronerben** [ocsigen/tyxml#302]
Hello, thanks for this fantastic project!

Currently, the `autocomplete` attribute only supports `on` and `off`. The [spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete) lists many more options. It would be nice if `Tyxml` supported those too! I don't know if this is already on the roadmap, or similar, so I decided to open this issue. :) 

Encoding all possibilities mentioned in the spec with types seems a bit tedious (as there seem to be named groups, special cases for hidden input fields, etc.). Maybe simply turning it into a `string` attribute is "good enough" (I don't know what `Tyxml`'s philosophy is here). 

Currently we've solved it by unsafely adding the attribute like so:
```ocaml
let open Tyxml_xml in
let open Tyxml_html in
street_input
|> toelt
|> amap1 (fun _ attrs ->
      add_string_attrib "autocomplete" "street_address" attrs)
|> tot)
```
where `street_input` is some input field.

**Comment by Drup** [comment]
That specification is indeed pretty awkward, but I would prefer to avoid "just using a string". In this case, it seems we could start with a fairly simple model such as ``` `On | `Off | `Tokens of string list ``` and see where that leads us. In any case the ppx extension can check more completely.

If you are willing, don't hesitate to submit a (potentially WIP) implementation ! There are instructions on how to add/change attributes in https://github.com/ocsigen/tyxml/blob/master/docs/Contributing.md . :)

**Comment by aronerben** [comment]
@Drup Thanks for the quick response! I've drafted a PR: https://github.com/ocsigen/tyxml/pull/303

**Comment by Drup** [comment]
Merged !
