### ISSUE TITLE
Missing constructors for text attributes

### ISSUE THREAD

**Issue by darioteixeira** [ocsigen/tyxml#70]
I'm not sure if this qualifies as a known issue, unknown issue, or just something I'm missing: in the [type defining the valid attributes](http://ocsigen.org/tyxml/3.4/api/Svg_types#TYPEtext_attr) for the SVG `text` element, one can find the variants `TextLength | Text_Anchor | Text_Decoration | Text_Rendering`.  Besides the lack of uniformity (CamelCase vs Snake_Case), note that [Svg_sigs.T](http://ocsigen.org/tyxml/3.4/api/Svg_sigs.T) declares the constructor function `a_textlength` for the first variant, but not for the others.

I can submit a pull request if you want.  It seems fairly straightforward to fix anyway.

**Comment by Drup** [comment]
Seems like it's missing indeed.

> I can submit a pull request if you want. It seems fairly straightforward to fix anyway.

Sure, go on.

**Comment by darioteixeira** [comment]
Btw, the casing of polymorphic variants is all over the place: some times CamelCase is used (`TextLength`), other times Snake_Case is used (`Color_Interpolation`), and other times Snake_case is used (`Color_profile`). Is there method to this madness, or is it just the result of slow accretion?

**Comment by darioteixeira** [comment]
Regarding the idiosyncratic casing: I've just noticed it mirrors the conventions used in the [W3C's docs](http://www.w3.org/TR/SVG11/) and [Mozilla's Developer docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute).  There seems to be some method to this madness after all...

**Comment by Drup** [comment]
You are absolutely right about high inconsistency in tyxml's naming scheme. This is partially due to the W3C's madness and partially internal to tyxml. It would be very worthwile if simple consistent rules were written and applied through the code base. This is the biggest thing holding the next tyxml version, but I don't have time to allocate to it.
