### ISSUE TITLE
The functor version is currently broken

### ISSUE THREAD

**Issue by vouillon** [ocsigen/tyxml#81]
I get this error:
```
Error: Error while linking /home/jerome/.opam/4.02.3/lib/tyxml/tyxml_f.cma(Html5_f):
Reference to undefined global `Xml'
```
I believe this is because we now to refer to `Xml.string_of_uri` in module `Wrapped_functions` in `html5_f.ml`.

I don't know how to fix that.

**Comment by vasilisp** [comment]
I don't understand the underlying issue, but a quick workaround is to remove the `Xml.string_of_uri` calls (branch `workaround-81`); `Xml.uri = string` and the conversion is the identity function.

**Comment by vasilisp** [comment]
@Drup, maybe there should be a `string_of_uri` in `Xml_print` instead of Xml? Is the current `string_of_uri` a placeholder for something that encodes special characters?

**Comment by vouillon** [comment]
The `Xml` module is not included in the functor version of the library...

**Comment by Drup** [comment]
Fixed by https://github.com/ocsigen/tyxml/pull/82
