### ISSUE TITLE
Comments, RAWTEXT, script data, etc., should not be escaped

### ISSUE THREAD

**Issue by aantron** [ocsigen/tyxml#90]
See the [specification](https://www.w3.org/TR/html5/syntax.html#serializing-html-fragments) for serialization.

However, this program

```ocaml
open Html5.M
open Html5.P

let () =
  print_list print_string
    [tot (Xml.comment "foo&");
     script (pcdata "foo&");
     style [pcdata "foo&"]]
```

produces this output:

```html
<!--foo&amp;--><script>foo&amp;</script><style>foo&amp;</style>
```

In particular, this seems to prevent comments such as:

```html
<!--[if IE 8]> <html class="no-js lt-ie9" lang="en"> <![endif]-->
```

being generated by expressions such as

```ocaml
tot (Xml.comment "[if IE 8]> <html class=\"no-js lt-ie9\" lang=\"en\"> <![endif]")
```

(credit to @sgrove for a query).

In the case of comments, if the user includes `-->` as text, we obviously have a problem if we "fix" this issue. Perhaps we can escape only those. Similarly, in RAWTEXT of a `style` tag, we may have to handle `</style>`.

Rather than fixing this immediately in TyXML, I propose that before TyXML 4.0,

- I split up Markup.ml into subpackages, or aliased modules, one of which will include the HTML writer, but exclude any other writers or parsers,
- I add a polyglot output mode to Markup.ml,
- Markup.ml (IIRC) already properly *doesn't* escape the above fragments, but we decide what to do about `-->` in comments, etc., and do it, or support doing it, in Markup.ml,
- we use Markup.ml's HTML writer to do the HTML writing.

This will leave us with only one place at which to maintain conformance with HTML5 and XHTML. It will add Markup.ml as a run-time dependency to projects using TyXML (as opposed to only build-time with the PPX). The split of Markup.ml into packages or aliased submodules should prevent the linking of unnecessary code into users' programs, such as the enormous HTML5 parser.

**Comment by Drup** [comment]
> It will add Markup.ml as a run-time dependency to projects using TyXML

This may not be true, Tyxml is currently split between the functor part and the concrete implementation. I have no problem adding dependencies to the concrete implementation (especially a printer) since it's not used inside eliom and js_of_ocaml.

**Comment by Drup** [comment]
This is now partially solved, for comments. Export to markup printer is still desirable but should be addressed in https://github.com/ocsigen/tyxml/issues/100

Unescaped data (for script/style) can be introduced with `Unsafe.data`.

**Comment by aantron** [comment]
Regarding `Unsafe.data`, I think the issue is a bit more complicated. For example, in a stylesheet, the text `</style>` is not allowed. So, if it is present, it should be escaped. Everything else is tokenized literally (no entity or character references).

Also, if `Unsafe.data` (or some other function) should be used for script or stylesheet data, the PPX should emit that instead of `pcdata` in the AST.
