### ISSUE TITLE
wiki content rendering error

### ISSUE THREAD

**Issue by agarwal** [ocsigen/tyxml#96]
In `functors.wiki`, the line:

```
The ##W## module in <<a_api | module Xml_sigs.T>> allows
```

renders on the website with an error:

```
The W module in Error a_api: invalid contents allows
```

**Comment by Drup** [comment]
Should be fixed now, not sure why it happened though.

**Comment by agarwal** [comment]
Maybe you already know, but it isn't live on the [website](http://ocsigen.org/tyxml/3.6/manual/functors#wrap) yet.

**Comment by Drup** [comment]
Yes, it will only be in the dev version: http://ocsigen.org/tyxml/dev/manual/functors

**Comment by agarwal** [comment]
Great, didn't know about the `dev` site.
