### ISSUE TITLE
suggestions that break backwards compatibility

### ISSUE THREAD

**Issue by agarwal** [ocsigen/tyxml#97]
Due to #95, I get the impression big changes are feasible. I'd like to suggest a few:

- Put all modules under a `Tyxml` namespace, and provide a `Tyxml.Std` module as the entry point to the API.
- Rename `T` module types to `S`. This is the norm.
- The term "wrap" isn't informative. If it is a monad, why not call it that. Thus some type names and module names could be changed.

@Drup Thank you for all your hard work! I especially respect your update to `intro.wiki`, which was terribly insufficient before.

**Comment by Drup** [comment]
Thanks! Indeed, I'm making all the various breaking change that I wanted to do for a while. 

The renaming is definitely going to happen before release. About wrap, if you look at the API, it's not necessarily a monad. It's just very common.

**Comment by Drup** [comment]
I won't rename `T` is `S` (both are equally regular, and one doesn't feel better than the other, so it's not important). `wrap` is neither a monad, and not even an `applicative` so it'll stay `wrap` for now.
The rest is done!

**Comment by agarwal** [comment]
Thanks.

**Comment by agarwal** [comment]
AFAICT, the latest tyxml still introduces many modules beginning with names like Html*, Svg*, and Xml*. My feeling is these shouldn't exist. _Every_ module should be prefixed by "Tyxml". This could be accomplished either by packing or manually naming modules with the prefix. I'd be happy with either method, but introducing numerous modules outside a single top prefix is undesirable: first it raises the chance of conflict with other libs in the future, and second it makes it difficult to know where the modules come from.

**Comment by Drup** [comment]
So, currently, we have different sublibraries. The most user-facing one is packed in the `Tyxml` module. I'm not sure how to name the pack for the other ones. Do you have propositions ?

**Comment by agarwal** [comment]
The convention I use would become the following for tyxml:

- There would be 1 packed module for each lib called respectively: Tyxml (for the main lib), Tyxml_ppx, Tyxml_parser, Tyxml_functor.
- The cma files would be named tyxml.cma, tyxml-ppx.cma, tyxml-parser.cma, etc. Given these are libraries providing a single packed module, it could also make sense to use underscores, tyxml_ppx.cma, but I prefer the dash personally.
- The findlib package organization is already correct I feel. However we do prefer to use findlib's "directory" field and put the files for each library in a sub-directory. This assures that various tools see only the minimal files when you specify a particular lib (for example, merlin will otherwise autocomplete on all modules in all libs even though you told it to look at just one lib). Also it's just clearer. Right now, I look at Tyxml's install dir, and I don't know which module is provided by which lib.

If you do this, you also open the possibility of renaming some modules. For example, if Html_f is packed into a module called Tyxml_functor, then the _f seems redundant.
