### ISSUE TITLE
link to _sigs modules in index

### ISSUE THREAD

**Issue by agarwal** [ocsigen/tyxml#98]
The `indexdoc` file doesn't link to `Xml_sigs`, `Html5_sigs`, and `Svg_sigs`. That would help, just so their existence is more readily obvious and you can get to them faster once you know they exist.

Right now you only find links to them if you investigate the docs for the functorial interface. Docs for the default interface only have things like `Html5_sigs.Make(Xml)(Svg.M).T`, but none of that is hyperlinked to the actual `Html5_sigs.T` signature you care about. You can click `Html5_sigs.Make`, so you do eventually get there, but a lot of links had to be traversed by then.

**Comment by Drup** [comment]
Both are already fixed by https://github.com/ocsigen/tyxml/pull/95

**Comment by agarwal** [comment]
Thanks.
