### ISSUE TITLE
4.0 Release list

### ISSUE THREAD

**Issue by Drup** [ocsigen/tyxml#99]
This is a TODO list to keep track of things.

General: 
- [x] Merge https://github.com/ocsigen/tyxml/pull/95
- [x] Fix https://github.com/ocsigen/eliom/issues/275
- [x] Make sure things are not completely broken
  - [x] For Eliom
  - [x] For other users (@darioteixeira, in particular).
- [ ] Implement template generation and provide ocamlbuild rules.
- [x] Ensure compat with 4.03

Doc
- [ ] Make a simple example of functor application (maybe simply redirect to `implem/` ?). Improve the relevant documentation.
- [x] Document the ppx, both standalone and inside the new tutorial.
- [x] Add ppx examples equivalent to the non-ppx examples.
- [x] Add a `Contributing.md` detailing how to add an attribute/element.

**Comment by darioteixeira** [comment]
Thanks for CCing me on this, @Drup. I'm tracking TyXml's master, and as of today (Tyxml's master is commit faef124) everything is fine.  Hopefully any upcoming breakage won't be too painful... ;-)

**Comment by Drup** [comment]
Release is getting closer, almost everything is done. Template generation (and better functorial doc) will be for the next time.

**Comment by darioteixeira** [comment]
The only breaking changes I've noticed were the `Html5.M` -> `Html5` renaming (ditto for `Svg`) and the new pretty-printing interface.  I've [already ported](https://github.com/darioteixeira/lambdoc/commit/26e725b7c237fd8ddcb942eba41936a9c3c9f265) Lambdoc to the new Tyxml API.

**Comment by vasilisp** [comment]
I have updated `js_of_ocaml` and `ocsigenserver` without any trouble (`tyxml` branches). Time for Eliom.

**Comment by Drup** [comment]
@vasilisp I was going to get to it, thanks!

**Comment by Drup** [comment]
ppx_tools is released, everything seems ready, and I'm getting restless. :)

**Comment by darioteixeira** [comment]
Everything looks fine on my end...
